package com.nacre.onlineShopping.dbutl;

public class QueryUtil {

	public static final String loginSelect = "select USER_ID, username,password from tbl_adminlogin where username=? and password=?";

	public static final String registrationInsert = "insert into table_registration(FIRST_NAME,LAST_NAME,EMAIL_ID,MOBILE_NO,PASSWORD,GENDER,ADDRESS_ID) values(?,?,?,?,?,?,?)";

	public static final String COUNTRYSELECT = "SELECT COUNTRY_ID,COUNTRY_NAME FROM TABLE_COUNTRY";

	public static final String STATESELECT = "SELECT STATE_ID,STATE_NAME FROM TABLE_STATE WHERE COUNTRY_ID=?";

	public static final String CITYGET = "SELECT CITY_ID,CITY_NAME FROM TABLE_CITY WHERE STATE_ID=?";

	public static final String ADDRESSINSERT = "INSERT INTO TABLE_ADDRESS(LINE1,LINE2,PINCODE,CITY_ID) VALUES(?,?,?,?)";

	public static final String GET_ROLE_FROM_TABLE_ROLE = "SELECT ROLE_ID,ROLE_NAME FROM TABLE_ROLE";

	public static final String INSERT_PRODUCT_DETAILS_TABLE_PRODUCT = "INSERT INTO TABLE_ADD_PRODUCTS(PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCRIPTION,PRODUCT_IMAGE,PRODUCT_ADD_DATE,PRODUCT_ADD_TIME,PRODUCT_QUANTITY,PRODUCT_COLOR,ADMIN_ID) VALUES(?,?,?,?,?,?,?,?,?)";

	public static final String INSERT_FEEDBACK_TABLE = "INSERT INTO TABLE_FEEDBACK(FEEDBACK_DESCRIPTION,PRODUCT_ID1,USER_ID) VALUES(?,?,?)";

	public static final String GET_EMAIL_PASSWORD = "SELECT USER_ID,EMAIL_ID,PASSWORD FROM TABLE_REGISTRATION WHERE EMAIL_ID=? AND PASSWORD =?";

	public static final String UPDATE_PASSWORD_USER = "UPDATE TABLE_REGISTRATION SET PASSWORD=? WHERE EMAIL_ID=?";

	public static final String UPDATE_PASSWORD_ADMIN = "UPDATE TBL_ADMINLOGIN SET PASSWORD=? WHERE USERNAME=?";

	public static final String GET_VIEW_PRODUCT_DETAILS = "SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCRIPTION,PRODUCT_COLOR,PRODUCT_QUANTITY,PRODUCT_ADD_DATE FROM TABLE_ADD_PRODUCTS";

	public static final String GET_VIEW_PRODUCT_DETAILS_FOR_USER = "SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_IMAGE,PRODUCT_COLOR,PRODUCT_QUANTITY FROM TABLE_ADD_PRODUCTS";

	public static final String INSERT_DATA_ADD_CART = "INSERT INTO TABLE_ADD_TO_CART (PRODUCT_PRICE,PRODUCT_QUANTITY,PRODUCT_PURCHAGE_DATE,PDID,USER_ID) VALUES(?,?,?,?,?)";

	public static final String GET_EDIT_PURPOSE_PRODUCT_DETAILS = "SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_DESCRIPTION,PRODUCT_ADD_DATE,PRODUCT_COLOR,PRODUCT_QUANTITY FROM TABLE_ADD_PRODUCTS WHERE PRODUCT_ID=? ";

	public static final String SAVE_EDITABLE_BY_ADMIN_PRODUCT_DATA = "UPDATE TABLE_ADD_PRODUCTS SET PRODUCT_NAME=?,PRODUCT_PRICE=?,PRODUCT_DESCRIPTION=?,PRODUCT_ADD_DATE=?, PRODUCT_ADD_TIME=?, PRODUCT_QUANTITY=?, PRODUCT_COLOR=?, ADMIN_ID=? WHERE PRODUCT_ID=?";

	public static final String INSERT_RATING_RATING_TABLR = "INSERT INTO TABLE_RATINGS (RATING,PRODUCT_ID,USER_ID)  VALUES(?,?,?)";

	public static final String GET_REGISTRATION_DETAILS_FOR_ORDER_SUMMARY = "SELECT FIRST_NAME,EMAIL_ID,MOBILE_NO FROM TABLE_REGISTRATION WHERE USER_ID=?";

	public static final String GET_USER_DATA_ORDER_SUMMARY = "select r.first_name,r.email_id,r.mobile_no, a.LINE1,a.LINE2,a.PINCODE,c.CITY_NAME,s.STATE_NAME,ca.COUNTRY_NAME from table_registration r join table_address a on r.ADDRESS_ID=a.ADDRESS_ID join table_city c on a.CITY_ID = c.CITY_ID join table_state s on s.STATE_ID=c.STATE_ID join table_country ca on s.COUNTRY_ID = ca.COUNTRY_ID where USER_ID=?";

	public static final String GET_PRODUCT_INFI_FOR_ADD_TO_CART = "SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,PRODUCT_QUANTITY FROM table_add_products WHERE PRODUCT_ID=?";

	public static final String INSERT_PRODUCT_USER_INFO_INTO_ADD_TO_CART = "INSERT INTO TABLE_ADD_TO_CART (PRODUCT_PRICE,PRODUCT_QUANTITY,PRODUCT_PURCHAGE_DATE,PDID,USER_ID) VALUES(?,?,?,?,?)";
    
	public static final String GET_REGISTRATION_DETAILS="SELECT FIRST_NAME,LAST_NAME,EMAIL_ID,MOBILE_NO,GENDER FROM table_registration";
     
	public static final String INSERT_VISITOR_META_DATA="INSERT INTO table_visitor(visitor_email,view_product_id) VALUES(?,?)";

	public static final String CHANGE_PASSWORD="UPDATE TABLE_REGISTRATION SET PASSWORD=? WHERE USER_ID=?";
}
